### ISSUE TITLE
[ISSUE] : Grid Layout Issue

### ISSUE THREAD

**Issue by saswatsamal** [hackclubiter/hacktheoctober#23]
![image](https://user-images.githubusercontent.com/39031660/135525583-dcd3c7d9-3b99-46db-a121-9fc20b3d6b84.png)

The grid in the project section is supposed to get rendered in a row but it is getting rendered one by one in a downward manner after the PR #22 .

**Comment by killua-24** [comment]
Can i work on this?

**Comment by saswatsamal** [comment]
Proceed

**Comment by killua-24** [comment]
Fixed Grid Layout and Improvised the structure #27

**Comment by killua-24** [comment]
Thank you.
