### ISSUE TITLE
[ISSUE] Navbar is not responsive for medium screens 

### ISSUE THREAD

**Issue by krishna9304** [hackclubiter/hacktheoctober#28]
<img width="994" alt="Screenshot 2021-10-01 at 1 07 09 PM" src="https://user-images.githubusercontent.com/71918441/135583159-71345c0f-dc10-452a-93e0-a7c7b28139ab.png">

There is this issue with the navbar that it is not displaying correctly in medium size screens.

**Comment by swetapadma15** [comment]
Can I work on this issue?

**Comment by krishna9304** [comment]
> Can I work on this issue?

Yes, go ahead.
