### ISSUE TITLE
Use Cloudinary for load balancing

### ISSUE THREAD

**Issue by Aniket762** [hackclubiter/hacktheoctober#38]
The application's loading time can be significantly increased if Cloudinary is used for asset management. Storing all the assets in the same server will make it heavy and hence increase the page load time. Would be great if the assets can be shifted to Cloudinary or any other free cloud asset management service. 

Also, I would say use https://squoosh.app/ for compressing your assets

**Comment by saswatsamal** [comment]
Okay cool. Since the site is meant for temporary use and it doesn't have many assets so we will use the current platform. But in our further projects, we will definitely use Cloudinary. 
Thanks for the suggestion. :)
